function split_behavioral_file(Trial_Idx_Split)

    % Description: function to split a behavioral file in two and save the
    % two files separately in the same folder. Filenames generated by the
    % file '_B1' will be renamed '_B1_1', '_B1_2', ..., '_B1_S'
    %   
    % Inputs: 
    %   - Trial_Idx_Split: Sx2 matrix, S=number of subsets. 
    %     e.g. [subset1_idx_start subset1_idx_end; 
    %           subset2_idx_start subset2_idx_end; ... ;
    %           subsetS_idx_start subsetS_idx_end] 
    %
    % Created by Simona Losacco on 20/01/2025

    % Set the initial directory and file filter
    initialDir = 'C:\'; % Change this to your desired initial directory
    fileFilter = {'*.mat'};

    [fileName, filePath] = uigetfile(fileFilter, 'Select a File', initialDir);
    InitialDataset = load(fullfile(filePath, fileName));

    
    for i = 1:size(Trial_Idx_Split, 1) % Loop on subsets

        TempDataset = InitialDataset;
        TempDataset.readme = 'This sub-dataset was automatically generated by the function split_behavioral_file';

        % Keep only the trials in the specified range 
        TempDataset.Cond_E_R = TempDataset.Cond_E_R(Trial_Idx_Split(i,1) : Trial_Idx_Split(i,2), :);
        TempDataset.CURSOR = TempDataset.CURSOR(:, Trial_Idx_Split(i,1) : Trial_Idx_Split(i,2));
        TempDataset.keypr = TempDataset.keypr(:, Trial_Idx_Split(i,1) : Trial_Idx_Split(i,2));
        TempDataset.keypr_ALL = TempDataset.keypr_ALL(:, Trial_Idx_Split(i,1) : Trial_Idx_Split(i,2));
        TempDataset.trials = structfun(@(x) x(Trial_Idx_Split(i,1) : Trial_Idx_Split(i,2)), TempDataset.trials, 'UniformOutput', false);
        TempDataset.nTrials = size(TempDataset.Cond_E_R, 1);


        % Save the new behavioral file
        NewFileName = regexprep(fileName, '_B1', sprintf('_B1_%d', i));
        save(fullfile(filePath, NewFileName), '-struct', 'TempDataset'); % Save it with the new name

    end

end


